require("user.packages")
require("user.vim-settings")
require("user.keybindings")
require("lsp.lsp")
require("lsp.cmp")
require("lsp.lsp-colors")
require("lsp.treesitter")
require("lsp.trouble")
require("customization.gruvbox")
require("customization.indent-blankline")
require("customization.lualine")
require("tools.harpoon")
require("tools.telescope")
require("tools.toggleterm")
require("tools.nvimtree")
require("tools.vgit")

