require("utils.packer-bootstrap") -- required
require("user.vim-settings")
require("user.keybindings")
require("tools.autopairs")
require("tools.harpoon")
require("tools.telescope")
require("tools.toggleterm")
require("tools.nvimtree")
require("tools.vgit")
require("lsp.treesitter")
require("lsp.lsp")
require("lsp.cmp")
require("lsp.trouble")
require("customization.sonokai")
require("customization.indent-blankline")
require("customization.lualine")

